type: PACKAGE
version: 1.3.0
name: create-self-signed-certificate Action package
description: Action package containing a script that will generate a self-signed certificate and an associate key on the device.
