type: PACKAGE
version: 1.0.1
name: bgp-monitor-per-stat Action package
description: Action package containing a script that checks BGP statistics on a per-stat basis are stable across a Change Control
